'use client';

import React from 'react';
import { DDIAnalysis } from '../lib/ai/schemas';

// Reuse DrugSearchResult interface minimally
interface DrugStub {
  name: string;
  genericName?: string;
}

interface PrintSummaryProps {
  report: DDIAnalysis | null;
  drug1: DrugStub | null;
  drug2: DrugStub | null;
}

// Helpers for color and scoring
function scoreToColor(score: number): string {
  if (score >= 70) return '#ef4444'; // danger
  if (score >= 40) return '#f59e0b'; // warning
  return '#10b981'; // success
}

function severityToScore(severity: string): number {
  switch (severity) {
    case 'contraindicated': return 96;
    case 'major':           return 80;
    case 'moderate':        return 54;
    case 'minor':           return 25;
    default:                return 8;
  }
}

export default function PrintSummary({ report, drug1, drug2 }: PrintSummaryProps) {
  if (!report || !drug1 || !drug2) return null;

  const score = severityToScore(report.severity);
  const color = scoreToColor(score);
  const isInteraction = report.overallStatus === 'interaction_detected';

  // Get current date/time in IST
  const now = new Date();
  const timestampIST = new Intl.DateTimeFormat('en-IN', {
    timeZone: 'Asia/Kolkata',
    dateStyle: 'long',
    timeStyle: 'medium',
  }).format(now) + ' IST';

  return (
    <div className="print-only print-summary-container" style={{ display: 'none', color: 'black', background: 'white', padding: '20px' }}>
      <style>{`
        @media print {
          .print-only { display: block !important; }
          .print-hide { display: none !important; }
          
          .print-summary-container {
            font-family: Arial, sans-serif;
            font-size: 11pt;
            color: #000;
          }
          .print-header {
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          .print-title {
            font-size: 24pt;
            font-weight: bold;
            margin: 0 0 5px 0;
            color: #111;
          }
          .print-meta {
            font-size: 10pt;
            color: #555;
            display: flex;
            justify-content: space-between;
          }
          .print-drugs {
            font-size: 14pt;
            font-weight: bold;
            background: #f0f0f0;
            padding: 10px;
            border-radius: 6px;
            margin-bottom: 20px;
            text-align: center;
          }
          .print-section {
            margin-bottom: 25px;
            page-break-inside: avoid;
          }
          .print-section h2 {
            font-size: 14pt;
            border-bottom: 1px solid #ccc;
            padding-bottom: 5px;
            margin-bottom: 10px;
            color: #222;
          }
          .print-card {
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 6px;
            margin-bottom: 10px;
            background: #fafafa;
            page-break-inside: avoid;
          }
          .static-bar-track {
            height: 12px;
            background: #eee;
            border-radius: 6px;
            width: 100%;
            margin-top: 4px;
            position: relative;
          }
          .static-bar-fill {
            height: 100%;
            border-radius: 6px;
            background: #888;
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
          }
          .static-bar-fill.d1 { background: #6366f1 !important; }
          .static-bar-fill.d2 { background: #06b6d4 !important; }
          
          .alt-list {
            list-style-type: disc;
            padding-left: 20px;
          }
          .alt-list li {
            margin-bottom: 8px;
          }
        }
      `}</style>

      {/* HEADER */}
      <div className="print-header">
        <h1 className="print-title">Clinical DDI Report</h1>
        <div className="print-meta">
          <span>Generated by Farma DDI Checker</span>
          <span>{timestampIST}</span>
        </div>
      </div>

      <div className="print-drugs">
        {drug1.name} <span style={{ color: '#888', margin: '0 10px' }}>+</span> {drug2.name}
      </div>

      {/* OVERVIEW */}
      <div className="print-section">
        <h2>Clinical Overview</h2>
        <div style={{ display: 'flex', alignItems: 'center', gap: '15px', marginBottom: '15px' }}>
          <div style={{
            padding: '8px 16px',
            border: `2px solid ${color}`,
            borderRadius: '20px',
            fontWeight: 'bold',
            textTransform: 'uppercase',
            color: color,
            printColorAdjust: 'exact',
            WebkitPrintColorAdjust: 'exact'
          }}>
            {report.severity} RISK ({score}/100)
          </div>
          <div><strong>Status:</strong> {isInteraction ? 'Interaction Detected' : 'No Major Interaction'}</div>
        </div>
        <p>{report.clinicalSignificance}</p>
        {report.potentialConsequences.length > 0 && (
          <ul style={{ paddingLeft: '20px', marginTop: '10px' }}>
            {report.potentialConsequences.map((c, i) => <li key={i}>{c}</li>)}
          </ul>
        )}
      </div>

      {/* MECHANISMS */}
      {report.interactionMechanisms.length > 0 && (
        <div className="print-section">
          <h2>Interaction Mechanisms</h2>
          {report.interactionMechanisms.map((m, i) => (
            <div key={i} className="print-card">
              <strong>{m.type}</strong>
              <p style={{ margin: '5px 0' }}>{m.explanation}</p>
              <div style={{ fontSize: '9pt', color: '#666' }}>Evidence: {m.evidence}</div>
            </div>
          ))}
        </div>
      )}

      {/* ADME CHART (Static version) */}
      <div className="print-section">
        <h2>ADME Comparison</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', maxWidth: '400px' }}>
          {['absorption', 'distribution', 'metabolism', 'excretion'].map(p => (
            <div key={p} style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
              <div style={{ width: '80px', textTransform: 'capitalize', fontSize: '10pt', fontWeight: 'bold' }}>{p}</div>
              <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <div className="static-bar-track">
                  <div className="static-bar-fill d1" style={{ width: `${report.admeScores.drug1[p as keyof typeof report.admeScores.drug1]}%` }} />
                </div>
                <div className="static-bar-track">
                  <div className="static-bar-fill d2" style={{ width: `${report.admeScores.drug2[p as keyof typeof report.admeScores.drug2]}%` }} />
                </div>
              </div>
            </div>
          ))}
        </div>
        <div style={{ display: 'flex', gap: '15px', marginTop: '10px', fontSize: '9pt', color: '#555' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
            <span style={{ width: '10px', height: '10px', background: '#6366f1', display: 'inline-block', printColorAdjust: 'exact', WebkitPrintColorAdjust: 'exact' }} /> {drug1.name}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
            <span style={{ width: '10px', height: '10px', background: '#06b6d4', display: 'inline-block', printColorAdjust: 'exact', WebkitPrintColorAdjust: 'exact' }} /> {drug2.name}
          </div>
        </div>
      </div>

      {/* TOXICITY & MONITORING */}
      <div className="print-section" style={{ display: 'flex', gap: '30px', flexWrap: 'wrap' }}>
        <div style={{ flex: '1 1 300px' }}>
          <h2>Organ Toxicity Scores</h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {['hepatic', 'renal', 'cardiac', 'neuro', 'hemato'].map(p => {
              const v1 = report.toxicityScores.drug1[p as keyof typeof report.toxicityScores.drug1];
              const v2 = report.toxicityScores.drug2[p as keyof typeof report.toxicityScores.drug2];
              return (
                <div key={p} style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
                  <div style={{ width: '60px', textTransform: 'capitalize', fontSize: '10pt', fontWeight: 'bold' }}>{p}</div>
                  <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '4px' }}>
                    <div className="static-bar-track">
                      <div className="static-bar-fill" style={{ width: `${v1}%`, background: scoreToColor(v1) }} />
                    </div>
                    <div className="static-bar-track">
                      <div className="static-bar-fill" style={{ width: `${v2}%`, background: scoreToColor(v2) }} />
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        <div style={{ flex: '1 1 300px' }}>
          <h2>Monitoring Requirements</h2>
          {report.monitoring.length > 0 ? report.monitoring.map((m, i) => (
            <div key={i} className="print-card">
              <strong>{m.parameter}</strong> {m.frequency && <span>({m.frequency})</span>}
              <p style={{ margin: '5px 0' }}>{m.reason}</p>
            </div>
          )) : <p>No specific monitoring required.</p>}
          
          <h2 style={{ marginTop: '20px' }}>Dose Risk Management</h2>
          <div className="print-card">
            {report.doseRisk.doseAdjustmentNeeded && <strong style={{ color: '#ef4444' }}>Dose Adjustment Required<br/></strong>}
            <strong>Dangerous Threshold:</strong> {report.doseRisk.dangerousDoseThreshold}<br/>
            <strong>Safe Guidance:</strong> {report.doseRisk.safeCoAdminGuidance}
          </div>
        </div>
      </div>

      {/* DEMOGRAPHICS */}
      <div className="print-section">
        <h2>Demographic Considerations</h2>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
          <div><strong>Pediatric:</strong> {report.demographicEffects.pediatric}</div>
          <div><strong>Geriatric:</strong> {report.demographicEffects.geriatric}</div>
          <div><strong>Hepatic Impairment:</strong> {report.demographicEffects.hepaticImpairment}</div>
          <div><strong>Renal Impairment:</strong> {report.demographicEffects.renalImpairment}</div>
          <div style={{ gridColumn: '1 / -1' }}><strong>Pregnancy/Lactation:</strong> {report.demographicEffects.pregnancyLactation}</div>
        </div>
      </div>

      {/* ALTERNATIVES LIST VIEW */}
      {report.alternatives.length > 0 && (
        <div className="print-section">
          <h2>Suggested Alternatives</h2>
          <ul className="alt-list">
            {report.alternatives.map((alt, i) => (
              <li key={i}>
                <strong>{alt.drugName}</strong> — <em>Risk: {alt.interactionRisk}</em><br/>
                {alt.rationale}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* DISCLAIMER */}
      <div style={{ marginTop: '40px', paddingTop: '10px', borderTop: '1px solid #aaa', fontSize: '9pt', color: '#666', fontStyle: 'italic' }}>
        CLINICAL DISCLAIMER: This report is AI-generated for informational and educational purposes only. It does not constitute medical advice and must not replace professional clinical judgment. Always consult a licensed pharmacist or physician before making prescribing decisions.
      </div>
    </div>
  );
}
